SELECT
site_id    site_id,
site_addr  site_addr,
site_full_ site_full_addr,
am_total   am_total,
am_peak_co am_count,
am_drive   am_drive,
am_walk    am_walk,
am_taxi    am_taxi,
am_bike    am_bike,
am_septa   am_septa,
pm_total   pm_total,
pm_peak_co pm_count,
pm_drive   pm_drive,
pm_walk    pm_walk,
pm_taxi    pm_taxi,
pm_bike    pm_bike,
pm_septa   pm_septa,
taz_no     taz_no,
area_sqft  area_sqft,
dwell_unit dwell_units,
comm_sqft  comm_sqft,
spaces_uni spaces_unit 
FROM sites_qgis

SELECT 
user_dvrpc site_id,
user_orig_ site_addr,
user_st_ad site_full_addr,
user_am_to am_total,
user_am_pe am_count,
user_am_dr am_drive,
user_am_wa am_walk,
user_am_ta am_taxi,
user_am_bi am_bike,
user_am_se am_septa,
user_pm_to pm_total,
user_pm_pe pm_count,
user_pm_dr pm_drive,
user_pm_wa pm_walk,
user_pm_ta pm_taxi,
user_pm_bi pm_bike,
user_pm_se pm_septa,
user_tazno taz_no,
user_area_ area_sqft,
user_dwell dwell_units,
user_comm_ comm_sqft,
user_space spaces_unit 
FROM sites_arcpro
WHERE user_dvrpc = 7

site_id,
site_addr,
site_full_addr,
am_total,
am_count,
am_drive,
am_walk,
am_taxi,
am_bike,
am_septa,
pm_total,
pm_count,
pm_drive,
pm_walk,
pm_taxi,
pm_bike,
pm_septa,
taz_no,
area_sqft,
dwell_units,
comm_sqft,
spaces_unit 