REM Delete these files at some point

del alias.php
del connectors.php
del countlocations.php
del crosswalks.php
del demandsegments.php
del desirelines.php
del detectors.php
del directions.php
del linerouteitems.php
del lineroutes.php
del lines.php
del links.php
del linktypes.php
del mainlines.php
del mainnodes.php
del mainturns.php
del mainzones.php
del matrices.php
del modes.php
del nodes.php
del operators.php
del paths.php
del pathsets.php
del screenlines.php
del signalcontrols.php
del signalgroups.php
del stages.php
del stopareas.php
del stoppoints.php
del stops.php
del territories.php
del test.php
del tickettypes.php
del timeprofileitems.php
del timeprofiles.php
del tollsystems.php
del tsystems.php
del turns.php
del validdayscont.php
del vehiclecombinations.php
del vehiclejourneyitems.php
del vehiclejourneys.php
del vehicleunits.php
del vehjouneysections.php
del zones.php